spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
spring.jpa.generate-ddl: true
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123


  thymeleaf:
    cache: false

welcome:
  message: Hello Thymeleaf
error:
  message: First Name & Last Name is required!